In [1]:
import torch

构建空矩阵

In [2]:
x = torch.empty(5,3)
print(x)

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 1.8049e-42, 0.0000e+00],
        [0.0000e+00, 4.1051e-41, 0.0000e+00]])


构建随机初始化的矩阵（随机数在0-1之间）

In [3]:
x = torch.rand(5,3)
print(x)

tensor([[0.8001, 0.2619, 0.7934],
        [0.9975, 0.2259, 0.1991],
        [0.0777, 0.9356, 0.9328],
        [0.9645, 0.0941, 0.1055],
        [0.4534, 0.5530, 0.6144]])


零矩阵

In [4]:
x = torch.zeros(5,3,dtype = torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


直接创建向量

In [5]:
x = torch.tensor([5.5,3])
y = torch.tensor([[5.5,5],[6,7]])
print(x)
print(y)

tensor([5.5000, 3.0000])
tensor([[5.5000, 5.0000],
        [6.0000, 7.0000]])


创建单位阵，以及根据原矩阵的形状创建新矩阵

In [6]:
x = torch.ones(5,3,dtype = torch.double)
y = torch.randn_like(x,dtype = torch.double)
print(y)
print(y.size())

tensor([[-0.7871, -1.7418,  0.0665],
        [ 0.2915, -0.9985, -0.6733],
        [ 0.9048, -0.5783,  0.1691],
        [ 0.5543, -1.0746,  0.9714],
        [-0.5986,  0.7763, -0.2846]], dtype=torch.float64)
torch.Size([5, 3])


矩阵运算

In [7]:
print(x+y)
print(torch.add(x,y))
result = torch.empty(5,3,dtype = torch.double)
torch.add(x,y,out = result)
x.add_(1)
print(x)
print(result)

tensor([[ 2.1295e-01, -7.4179e-01,  1.0665e+00],
        [ 1.2915e+00,  1.5160e-03,  3.2672e-01],
        [ 1.9048e+00,  4.2167e-01,  1.1691e+00],
        [ 1.5543e+00, -7.4602e-02,  1.9714e+00],
        [ 4.0144e-01,  1.7763e+00,  7.1539e-01]], dtype=torch.float64)
tensor([[ 2.1295e-01, -7.4179e-01,  1.0665e+00],
        [ 1.2915e+00,  1.5160e-03,  3.2672e-01],
        [ 1.9048e+00,  4.2167e-01,  1.1691e+00],
        [ 1.5543e+00, -7.4602e-02,  1.9714e+00],
        [ 4.0144e-01,  1.7763e+00,  7.1539e-01]], dtype=torch.float64)
tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]], dtype=torch.float64)
tensor([[ 2.1295e-01, -7.4179e-01,  1.0665e+00],
        [ 1.2915e+00,  1.5160e-03,  3.2672e-01],
        [ 1.9048e+00,  4.2167e-01,  1.1691e+00],
        [ 1.5543e+00, -7.4602e-02,  1.9714e+00],
        [ 4.0144e-01,  1.7763e+00,  7.1539e-01]], dtype=torch.float64)


改变矩阵形状

In [8]:
x = torch.randn(4,4)
temp1 = x.view(16)
temp2 = x.view(-1,8)
print(temp1.size())
print(temp2.size())

torch.Size([16])
torch.Size([2, 8])


杂项

In [9]:
x = torch.randn(1)
print(x)
print(x.item()) #获取单一元素的值

tensor([-2.1348])
-2.134782314300537


pytorch与numpy之间的转化

In [10]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(a)
print(b)
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


pytorch数值与numpy数值之间共享内存

In [11]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]
