In [2]:
import torch

用requires_grad确定是否参与求导

In [4]:
x = torch.ones(2,2,requires_grad = True)
z = torch.ones(2,1,requires_grad = True)
print(z)

tensor([[1.],
        [1.]], requires_grad=True)


In [17]:
y = x.mm(z)+2 #mm是矩阵相乘
#y = x-z+2
print(y) #此处y带着反向求导的函数 即AddBackward0
y.backward(torch.tensor([[1.0,],[2.0]])) #由于向量对向量求导产生的是雅可比矩阵，无法直接落到某一个向量上，因此需要一个向量参数使得两边形状相同
print(z.grad)
z.grad.data.zero_()

tensor([[4.],
        [4.]], grad_fn=<AddBackward0>)
tensor([[3.],
        [3.]])


tensor([[0.],
        [0.]])

用with torch.no_grad() 可以使得变量不参与求导

In [46]:
print(x.requires_grad)
print((x**2).requires_grad)
with torch.no_grad():
    print((x*x).requires_grad)

True
True
False
